### ISSUE TITLE
Warnings on 64-bit Windows

### ISSUE THREAD

**Issue by superbobry** [s-yata/marisa-trie#2]
Hello,

I'm one of the maintainers of the [Python bindings](https://github.com/kmike/datrie) to `marisa-trie`. Recently we started testing the code on Windows and came across a [known](https://code.google.com/archive/p/marisa-trie/issues/18) issue with the 64-bit version. The library compiles with a number of invalid-cast warnings, but most of the tests fail to pass, which may indicate that despite successful compilation, the library is broken.

Here's a sample of the compilation warnings:

```
lib/marisa/grimoire/vector\bit-vector.cc(771) : warning C4267: 'argument' : conversion from 'size_t' to 'const marisa::UInt32', possible loss of data
lib/marisa/grimoire/vector\bit-vector.cc(776) : warning C4267: 'argument' : conversion from 'size_t' to 'const marisa::UInt32', possible loss of data
lib/marisa/grimoire/vector\bit-vector.cc(815) : warning C4267: 'argument' : conversion from 'size_t' to 'const marisa::UInt32', possible loss of data
```

You can see full compilation log [on AppVeyor](https://ci.appveyor.com/project/superbobry/marisa-trie/build/job/5j11hy5b5fjdfpnu).

**Comment by s-yata** [comment]
Thank you for your report.
Warnings to narrowing conversion may not be the cause of test failures.
I'll check tests later.

**Comment by s-yata** [comment]
I added explicit typecasts to suppress warnings for narrowing conversion.
Would you check whether it sill compiles with a number of invalid-cast warning?

In addition, I'm not sure but some errors might be due to the file mode.
https://github.com/kmike/marisa-trie/issues/1#issuecomment-198243103

**Comment by s-yata** [comment]
Sorry, it must not be due to the file mode, because it passes tests on 32-bit environments.

**Comment by s-yata** [comment]
It seems that the following decrement is wrong.
https://github.com/s-yata/marisa-trie/blob/master/lib/marisa/grimoire/vector/bit-vector.cc#L200

**Comment by s-yata** [comment]
Would you check if tests still fail or not with the latest version?

**Comment by superbobry** [comment]
Yes, with the `master` version of `marisa-trie` all the 64-bit tests [succeed](https://ci.appveyor.com/project/superbobry/marisa-trie/build/25). Thank you very much! 

Can you do a bugfix release?

**Comment by s-yata** [comment]
I'll do it in a few days.

**Comment by superbobry** [comment]
Just a friendly reminder that we're waiting on the new release to update the Python wrapper :)

**Comment by s-yata** [comment]
Sorry for my very very late reaction.

I've added a tag v0.2.5.

https://github.com/s-yata/marisa-trie/releases/tag/v0.2.5

**Comment by superbobry** [comment]
No worries. Thank you for releasing the fix!

**Comment by s-yata** [comment]
I've added a release v0.2.5.

https://github.com/s-yata/marisa-trie/releases/tag/v0.2.5

marisa-0.2.5.tar.gz is an archive generated by `make dist`.
