### ISSUE TITLE
MARISA_IO_ERROR: file_ == INVALID_HANDLE_VALUE

### ISSUE THREAD

**Issue by superbobry** [s-yata/marisa-trie#3]
We've managed to spot one more issue with Windows support in `marisa-trie`. `Trie.write` fails with 

```
lib/marisa/grimoire/io\mapper.cc:127: MARISA_IO_ERROR: file_ == INVALID_HANDLE_VALUE
```

You can see the Python test case causing the error [here](https://ci.appveyor.com/project/superbobry/marisa-trie/build/2/job/qbco27n667cxk6u6).

**Comment by s-yata** [comment]
This exception `MARISA_IO_ERROR: file_ == INVALID_HANDLE_VALUE` means it failed to open a file.
Could you check whether the file `fname` exists at that time?

**Comment by superbobry** [comment]
Thank you. I've managed to nail down the issue using `GetLastError`, which returned [`ERROR_SHARING_VIOLATION`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681382(v=vs.85).aspx). The sharing violation was caused by the way test file are created:

```python
fd, fname = tempfile.mkstemp()  # !
words = get_random_words(1000)
trie = marisa_trie.Trie(words)
with open(fname, 'wb') as f:
    trie.write(f)

# To fix do ``os.close(fd)``.
trie2 = marisa_trie.Trie()
trie2.mmap(fname)
``` 

Note that the test file remains open until the moment it gets mmaped by `marisa-trie`. Closing the file handle eliminated the error.

**Comment by s-yata** [comment]
Thank you for your detailed report.
I'm happy to hear that the problem has been fixed.
