### ISSUE TITLE
How can I do search?

### ISSUE THREAD

**Issue by Ingsuifon** [s-yata/marisa-trie#51]
I find the function `_find`, but I think it is an internal function and I don't know how to use it, is it right ? `_find(key, 0, 0, len(key))`

**Comment by jmr** [comment]
I don't see `_find`. Where is it?

Does `Trie::lookup` do what you want?

https://www.s-yata.jp/marisa-trie/docs/readme.en.html

https://github.com/s-yata/marisa-trie/blob/006020c1df76d0d7dc6118dacc22da64da2e35c4/include/marisa/trie.h#L34

**Comment by Ingsuifon** [comment]
Sorry, this is the problem of cedar, I asked the wrong place.
