### ISSUE TITLE
Building instructions

### ISSUE THREAD

**Issue by superbobry** [s-yata/marisa-trie#6]
These might be helpful for people unfamiliar with autoconf & automake.

**Comment by s-yata** [comment]
I use `autoreconf -i` instead of `automake` and `autoconf`.
I think it should be documented.

**Comment by superbobry** [comment]
Yep, that would be great. The content of `INSTALL` is currently too generic to be useful.

**Comment by s-yata** [comment]
I added simple building instructions to README.md.

**Comment by superbobry** [comment]
Thank you!
